version: "0.2"
files:
  - "**/*"
dictionaryDefinitions:
  - name: cmake-refined
    path: ./config/cmake-refined-words.txt
    addWords: false
  - name: qt
    path: ./config/qt-words.txt
    addWords: false
  - name: linux-package
    path: ./config/linux-package-words.txt
    addWords: false
  - name: taskfile
    path: ./config/taskfile-words.txt
    addWords: false
dictionaries:
  - qt
  - taskfile
  - bash
  - cmake-refined
  - cpp-refined
  - docker
  - linux-package
  - python-common
ignorePaths:
  - s**/node_modules/**
  - "**/vscode-extension/**"
  - "**/.git/**"
  - .github/actions/**
  - .github/workflows/**
  - cmake/modules/**
  - docs/api-docs/**
  - cspell.config.yaml
  - "*.gz"
  - "*.lock"
  - "*.svg"
  - .gitignore
  - .devcontainer/.dockerignore
  - .vscode
  - megalinter
  - package-lock.json
  - report
  - pnpm-lock.yaml
  - dist/**
  - build/**
  - /project-words.txt
  - ./qt-words.txt
  - ./taskfile-words.txt
  - ./cmake-refined-words.txt
  - ./linux-package-words.txt
useGitignore: true
language: en, en-GB, de, de-DE
allowCompoundWords: true
enableGlobDot: true
words:
  - APPL
  - aqtinstall
  - ARGN
  - cbproj
  - ccache
  - ccmake
  - clangd
  - cmakelang
  - Codacy
  - codecov
  - cppcheck
  - cppstd
  - cpptools
  - cschlosser.doxdocgen
  - DCOMPONENT
  - Devel
  - DOPTION*
  - DPROJECT
  - eamodio
  - fasterer
  - FILEOS
  - fips
  - fprofile
  - ftest
  - furo
  - Fuzzer
  - Gcov
  - giticket
  - groupproj
  - gtest
  - hmarr
  - hwrap
  - icns
  - IHELP
  - IOPTIONS
  - IQUIT
  - IWYU
  - jamf
  - jinja
  - jmbde
  - jmuelbert
  - juergen
  - kramdown
  - kwarg
  - kwargs
  - LCOV
  - libcxx
  - libfmt
  - libgmp
  - libmpfr
  - libspdlog
  - lstrip
  - muelbert
  - Mülbert
  - munki
  - munkiadmin
  - munkipkg
  - myclass
  - noqa
  - oclint
  - parg
  - pargs
  - Pavlik
  - Pboard
  - pipenv
  - pkgsinfo
  - plists
  - pthread
  - pthreads
  - PTRACE
  - pylance
  - pyyaml
  - qtconanboilerplate
  - qtwidgettest
  - REDIST
  - rubocop
  - SAST
  - sectnums
  - socat
  - sonarqube
  - spdlog
  - svgz
  - SYSREQUIRES
  - twxs
  - uncrustify
  - venv
  - VRAC
  - webp
  - Wextra
  - Wignored
  - winver
  - Wmaybe
  - Wmissing
  - Wpedantic
  - Wreorder
  - Wreturn
  - Wuninitialized
  - Wunused
  - xcodeproj
flagWords:
  - hte
