source "https://rubygems.org"
gemspec
gem install bundler
gem 'jekyll-archives'
gem "jekyll-sitemap"
gem "rake"
gem "public_suffix"
gem "addressable"
gem "faraday"
gem "ffi"
gem "google-protobuf"
gem "i18n"
gem "sass-embedded"
gem "jekyll-sass-converter"
gem "jrexml"
gem "jkramdown"
gem "jmercenary"
gem "jrouge"
gem "junicode-display_width"
gem "jterminal-table"
gem "jwebrick"
gem "jjekyll"
gem "jjekyll-archives"
gem "jjekyll-feed"
